name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@a02a9fd9c745eb84acab628da2d5b7a24f86a603 # v5
        with:
          release-type: node
